CREATE TABLE IF NOT EXISTS dm.dm_account_turnover_f(
    account_rk DECIMAL(23,8),
    credit_amount DECIMAL(23,8),
    credit_amount_rub DECIMAL(23,8),
    debet_amount DECIMAL(23,8),
    debet_amount_rub DECIMAL(23,8)
) PARTITIONED BY (on_date DATE) STORED AS PARQUET;
CREATE TABLE IF NOT EXISTS dm.dm_account_balance_f(
    account_rk DECIMAL(38,8),
    balance_out DECIMAL(38,8),
    balance_out_rub DECIMAL(38,8)
) PARTITIONED BY (on_date DATE) STORED AS PARQUET;
CREATE TABLE IF NOT EXISTS dm.dm_f101_round_f(
    CHAPTER STRING,
    LEDGER_ACCOUNT STRING,
    CHARACTERISTIC STRING,
    BALANCE_IN_RUB DECIMAL(38,8),
    R_BALANCE_IN_RUB DECIMAL(38,8),
    BALANCE_IN_VAL DECIMAL(38,8),
    R_BALANCE_IN_VAL DECIMAL(38,8),
    BALANCE_IN_TOTAL DECIMAL(38,8),
    R_BALANCE_IN_TOTAL DECIMAL(38,8),
    TURN_DEB_RUB DECIMAL(38,8),
    R_TURN_DEB_RUB DECIMAL(38,8),
    TURN_DEB_VAL DECIMAL(38,8),
    R_TURN_DEB_VAL DECIMAL(38,8),
    TURN_DEB_TOTAL DECIMAL(38,8),
    R_TURN_DEB_TOTAL DECIMAL(38,8),
    TURN_CRE_RUB DECIMAL(38,8),
    R_TURN_CRE_RUB DECIMAL(38,8),
    TURN_CRE_VAL DECIMAL(38,8),
    R_TURN_CRE_VAL DECIMAL(38,8),
    TURN_CRE_TOTAL DECIMAL(38,8),
    R_TURN_CRE_TOTAL DECIMAL(38,8),
    BALANCE_OUT_RUB DECIMAL(38,8),
    R_BALANCE_OUT_RUB DECIMAL(38,8),
    BALANCE_OUT_VAL DECIMAL(38,8),
    R_BALANCE_OUT_VAL DECIMAL(38,8),
    BALANCE_OUT_TOTAL DECIMAL(38,8),
    R_BALANCE_OUT_TOTAL DECIMAL(38,8)
) PARTITIONED BY ( FROM_DATE DATE, TO_DATE DATE) STORED AS PARQUET;